theme: minimal-mistakes-jekyll

defaults:
    - scope:
        path: ""
        type: posts
      values:
        layout: single
    - scope:
        path: ""
        type: pages
      values:
        layout: single
